name: Reusable Sonatype SCA

on:
  workflow_call:
    inputs:
      application_id:
        description: Sonatype Lifecycle application public ID
        required: true
        type: string
      stage:
        description: Evaluation stage
        required: false
        type: string
        default: build
      scan_targets:
        description: Space-separated scan targets
        required: false
        type: string
        default: package.json package-lock.json
      runner:
        description: Runner label
        required: false
        type: string
        default: ubuntu-latest
      upload_result_artifact:
        description: Upload scanner result artifact
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  security-events: write

jobs:
  sonatype:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Sonatype evaluate
        id: run-iq-cli
        uses: sonatype/actions/evaluate@v1
        with:
          iq-server-url: ${{ vars.LIFECYCLE_SERVER_URL }}
          username: ${{ vars.LIFECYCLE_USERNAME }}
          password: ${{ secrets.LIFECYCLE_PASSWORD }}
          application-id: ${{ inputs.application_id }}
          stage: ${{ inputs.stage }}
          scan-targets: ${{ inputs.scan_targets }}

      - name: Upload Result File as an artifact
        if: ${{ inputs.upload_result_artifact && !cancelled() && steps.run-iq-cli.outputs.result-file-path }}
        uses: actions/upload-artifact@v3
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
        with:
          name: result-file
          path: ${{ steps.run-iq-cli.outputs.result-file-path }}
